<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" alt="CLRSWY_LOGO" title="Open and Execute in Google Colaboratory"></a><br/>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
# YOUR CODE IS HERE

my_list = [5, 10, 15, 20, 25]

np.array(my_list)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [3]:
# YOUR CODE IS HERE

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [4]:
# YOUR CODE IS HERE
np.ones((4, 4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [6]:
# YOUR CODE IS HERE

np.ones((4, 4), dtype='int')+6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [7]:
# YOUR CODE IS HERE

np.full((4, 4), 7, dtype='int')

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (both inclusive). 

In [8]:
# YOUR CODE IS HERE

np.arange(2, 17, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive).

In [9]:
# YOUR CODE IS HERE

np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive) using linspace method.

In [12]:
# YOUR CODE IS HERE

np.linspace(0, 24, 25, dtype='int').reshape(5, 5)
np.linspace(0, 25, 25, dtype='int', endpoint=False).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [11]:
# YOUR CODE IS HERE

np.random.rand(5)

array([0.01058767, 0.93719118, 0.376576  , 0.55491094, 0.01423433])

### 11. Generate a 5 by 5 array and fills it with random values as per the standard normal distribution.


In [13]:
# YOUR CODE IS HERE
np.random.randn(5, 5)


array([[ 1.26384833,  1.16714628, -0.43789896, -1.52338529,  0.96948179],
       [-1.33952558, -0.80389006, -2.1366359 , -0.98337253,  0.49941278],
       [ 1.58491387, -0.93549856, -1.31150078, -1.13902393,  0.1884007 ],
       [ 0.69563711,  0.33497679, -0.1042397 , -0.82080458, -0.40784599],
       [-1.94652745, -0.34608163,  1.42479924,  0.5912967 ,  0.84710048]])

### 12. Generate a 3*4 array of random int numbers between 20 and 50 (both inclusive).

In [14]:
# YOUR CODE IS HERE

np.random.randint(20, 51, size=(3, 4))

array([[20, 33, 34, 30],
       [36, 41, 42, 34],
       [36, 24, 43, 33]])

### 13. Generate an array named "ranarr"consisting of randomly 48 numbers (int) and reshape this array 6 by 8 in different ways (remember the power of -1).

In [15]:
# YOUR CODE IS HERE
ranarr = np.random.randint(0, 60, 48)
ranarr


array([18, 35, 33,  2, 19,  8,  8, 56, 45,  7, 53, 49, 23, 58, 19, 49, 26,
       48, 41,  1, 50,  7, 15, 25, 59, 45, 28, 11, 16, 17, 20, 41, 58, 57,
       12, 35, 45, 32, 28, 57, 43, 50, 38, 27, 42, 26, 42,  2])

In [16]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6, 8)

array([[18, 35, 33,  2, 19,  8,  8, 56],
       [45,  7, 53, 49, 23, 58, 19, 49],
       [26, 48, 41,  1, 50,  7, 15, 25],
       [59, 45, 28, 11, 16, 17, 20, 41],
       [58, 57, 12, 35, 45, 32, 28, 57],
       [43, 50, 38, 27, 42, 26, 42,  2]])

In [17]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(-1, 8)


array([[18, 35, 33,  2, 19,  8,  8, 56],
       [45,  7, 53, 49, 23, 58, 19, 49],
       [26, 48, 41,  1, 50,  7, 15, 25],
       [59, 45, 28, 11, 16, 17, 20, 41],
       [58, 57, 12, 35, 45, 32, 28, 57],
       [43, 50, 38, 27, 42, 26, 42,  2]])

In [18]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
ranarr.reshape(6, -1)


array([[18, 35, 33,  2, 19,  8,  8, 56],
       [45,  7, 53, 49, 23, 58, 19, 49],
       [26, 48, 41,  1, 50,  7, 15, 25],
       [59, 45, 28, 11, 16, 17, 20, 41],
       [58, 57, 12, 35, 45, 32, 28, 57],
       [43, 50, 38, 27, 42, 26, 42,  2]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [19]:
# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [20]:
# YOUR CODE IS HERE 
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [21]:
# YOUR CODE IS HERE 
mat[:, 0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [22]:
# YOUR CODE IS HERE 
mat[1, ::2]
mat[1, 0:3:2]

array([5, 7])

### 17. Assign 77 to every cell in 3rd column (index number 2).

In [23]:
# YOUR CODE IS HERE 
mat[:, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take the value at the 2nd row (index number 1) and 1st column (index number 0) & (b) the value at the 4th row (index number 3) and 3rd column (index number 2) at the same time.

In [24]:
# YOUR CODE IS HERE 
mat[[1, 3], [0, 2]]

array([ 5, 77])

### 19. What are the common values present at the intersection of the second (index number 1) and last (index number 3) row with a step size of 2 and the first (index number 0) and last column with a step size of 2 in the given array?

In [25]:
# YOUR CODE IS HERE 
mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [26]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [27]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [28]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [29]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [30]:
# YOUR CODE IS HERE 

(mat[mat<10] + mat[mat>12]).std()

np.std(mat[mat<10] + mat[mat>12])

29.700546274093877

### 22. Get the sum of the values at the 2nd column (index number 1) in the original "mat".

In [31]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [32]:
# LET US GET BACK THE ORIGINAL ARRAY OF "mat" AGAIN

# YOUR CODE IS HERE 

mat[:, 2] = [3, 7, 11, 15]
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
# YOUR CODE IS HERE 

mat[:, 1].sum(axis=0)

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [34]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

third_column = mat[:, 2:3]
third_column

array([[ 3],
       [ 7],
       [11],
       [15]])

In [36]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 


third_row = mat[2]
third_row

array([ 9, 10, 11, 12])

In [38]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

print(np.median(third_column))
print(np.median(third_row))



9.0
10.5


In [39]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(third_column))
print(np.mean(third_row))

9.0
10.5


In [40]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

print(np.std(third_column))
print(np.std(third_row))

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [49]:
# YOUR CODE IS HERE 

import pandas as pd

In [ ]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.

In [ ]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

sal = pd.read_csv('Salaries.csv')

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
sal.head()


Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

sal.sample()

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 
sal.info()


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 

sal.describe()

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 

sal["Year"].value_counts(dropna=False)

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

sal["Year"].value_counts(dropna=False).nunique()

In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
sal["Year"].unique()


### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 

sal["TotalPay"].max()

In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 

sal["TotalPay"].mean()

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 

sal[sal["TotalPay"] > sal.TotalPay.mean()]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 

len(sal[sal["TotalPay"] > sal["TotalPay"].mean()])

### How much does ALBERT PARDINI make money (including extras, benefits, etc)?

In [ ]:
# YOUR CODE IS HERE 

sal[sal['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 

sal[sal.TotalPayBenefits == sal.TotalPayBenefits.min()]['EmployeeName']

### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 

sal["JobTitle"].unique()

### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 

sal['JobTitle'].value_counts().tail(3)

### How many people earned more than avg in 2012? (including extras, benefits, etc)

In [ ]:
# YOUR CODE IS HERE 
more_than_avg = sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.mean()) & (sal.Year == 2012)]
more_than_avg['EmployeeName'].nunique()


### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 

len(sal[sal.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 

sal_new = sal.iloc[:, [0, 1, 2, 7, 8]]
sal_new

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 

sal_new = sal_new.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]\
                                                                         [['EmployeeName', 'TotalPayBenefits']]


Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">THE END OF THE ASSIGNMENT 02</p>

# Now. it's time to relax!

![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

___

<a href="https://clarusway.com/"><img align="center" src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" alt="CLRSWY_LOGO" title="Way to Reinvent Yourself"></a><br/>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>